### PR TITLE
No Bakes II

### PR DESCRIPTION
**Pull request by jas58**
#1 trying to see why it didn't display the recipe text or image.  renamed image file away from "ingredients" in case that had confused things.

### CODE REVIEW

**Comment by jas58** [comment]
Do I close this?  It's a red check mark and exclamation point in a circle on the button.

**Comment by chrisdaaz** [comment]
@jas58 thanks for letting me know it wasn't working. [i fixed it](https://github.com/chrisdaaz/forking/commit/7246d2248be913f980fe6b278124575aa4e31d08). it was a YAML syntax error. no biggie.

https://chrisdaaz.github.io/forking/recipes/no-bakes.html

**Comment by jas58** [comment]
Thanks for linking the revision.  On one hand I feel more confused, but I'm practicing boundaries and recall this lesson is not about YAML.  I think I misunderstood when to type my own hyphens and when the editor would magically provide them?

On the other, I'm wondering what part of the screens I saw last week should have told me I had not pushed any of the code through?  If I find that step, I'll try to share the screen cap.

Gratefully,
Jennifer

**Comment by chrisdaaz** [comment]
If you're interested in learning more about YAML, this is a really good video (in years of writing YAML, I've only ever needed what's covered in the first 6 minutes, fyi): https://youtu.be/cdLNKUoMc6c

Let me know if you find a screen cap that I can help explain.

**Pull request closed without merging**
